import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

const outfitSans = Outfit({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<TRPCReactProvider>
			<html lang="en" suppressHydrationWarning className="dark">
				<body className={`${outfitSans.variable} antialiased`}>
					{children}
				</body>
			</html>
		</TRPCReactProvider>
	);
}
